"""
test_documentation.py
Test terhadap halaman dokumentasi teknis: banyak code block,
tabel parameter, sidebar navigasi tebal yang harus dibuang.

Modul ini menguji kemampuan pipeline dalam menangani struktur HTML
khas dokumentasi API atau library (seperti ReadTheDocs, Docusaurus, MkDocs)
yang sering memiliki sidebar navigasi besar, tabel parameter kompleks,
dan blok kode dengan syntax highlighting.
"""

import pytest
from bs4 import BeautifulSoup

# Import komponen yang diuji
from webfetch.cleaner import DOMCleaner
from webfetch.scoring import ContentScorer
from webfetch.content import MainContentDetector
from webfetch.semantic import SemanticExtractor
from webfetch.model import CodeBlock, TableBlock

# Sample HTML Halaman Dokumentasi
SAMPLE_DOCS_HTML = """
<html>
<head>
    <title>API Reference - Config Class</title>
</head>
<body>
    <!-- Sidebar Navigasi (Noise) -->
    <nav class="sidebar">
        <ul>
            <li><a href="/intro">Introduction</a></li>
            <li><a href="/install">Installation</a></li>
            <li><a href="/api">API Reference</a></li>
            <!-- Banyak link lain -->
            <li><a href="/v1/old">Old Docs v1</a></li>
            <li><a href="/v2/old">Old Docs v2</a></li>
        </ul>
        <div class="ad-sidebar">Download PDF Version</div>
    </nav>

    <!-- Konten Utama Dokumentasi -->
    <main class="document-content">
        <h1>Config Class Reference</h1>
        <p>Kelas <code>Config</code> digunakan untuk mengatur parameter global aplikasi.</p>

        <h2>Constructor</h2>
        <pre><code class="language-python">def __init__(self, path: str, debug: bool = False):
    self.path = path
    self.debug = debug</code></pre>

        <h2>Parameters</h2>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>path</td>
                    <td>str</td>
                    <td>Lokasi file konfigurasi.</td>
                </tr>
                <tr>
                    <td>debug</td>
                    <td>bool</td>
                    <td>Aktifkan mode debug verbose.</td>
                </tr>
            </tbody>
        </table>

        <h2>Contoh Penggunaan</h2>
        <pre><code class="language-javascript">const config = new Config('/etc/app.json', true);
config.load();</code></pre>
    </main>

    <!-- Footer -->
    <footer>
        <p>Generated by Sphinx</p>
    </footer>
</body>
</html>
"""

def test_code_block_language_detected():
    """Pastikan class 'language-python' dsb terbaca jadi block.language."""
    
    soup = BeautifulSoup(SAMPLE_DOCS_HTML, 'html.parser')
    
    # 1. Deteksi Konten Utama
    scorer = ContentScorer()
    detector = MainContentDetector(scorer=scorer)
    detection = detector.detect(soup, str(soup))
    
    assert detection['element'] is not None, "Konten utama (<main>) harus ditemukan"
    
    # 2. Ekstraksi Semantik
    extractor = SemanticExtractor()
    blocks = extractor.extract_all(detection['element'])
    
    # 3. Filter Code Blocks
    code_blocks = [
        b for b in blocks 
        if isinstance(b, CodeBlock) or (hasattr(b, 'type') and str(b.type) in ['code', 'BlockType.CODE'])
    ]
    
    assert len(code_blocks) >= 2, "Harus menemukan minimal 2 blok kode (Python & JS)"
    
    # 4. Validasi Bahasa
    python_found = False
    js_found = False
    
    for block in code_blocks:
        # Akses atribut language (handle jika objek custom atau dataclass)
        lang = getattr(block, 'language', None)
        code_text = getattr(block, 'code', '')
        
        if lang == 'python':
            python_found = True
            assert "__init__" in code_text, "Kode Python harus berisi definisi kelas/fungsi"
            
        elif lang == 'javascript':
            js_found = True
            assert "new Config" in code_text, "Kode JS harus berisi instansiasi objek"
            
    assert python_found, "Blok kode Python dengan language='python' harus terdeteksi"
    assert js_found, "Blok kode JavaScript dengan language='javascript' harus terdeteksi"


def test_sidebar_navigation_removed():
    """Pastikan sidebar/nav dokumentasi tidak ikut ke main content."""
    
    soup = BeautifulSoup(SAMPLE_DOCS_HTML, 'html.parser')
    
    # 1. Clean DOM dulu untuk menghapus tag non-konten eksplisit
    cleaner = DOMCleaner()
    cleaner.clean(soup)
    
    # 2. Deteksi Konten Utama
    scorer = ContentScorer()
    detector = MainContentDetector(scorer=scorer)
    detection = detector.detect(soup, str(soup))
    
    main_elem = detection['element']
    assert main_elem is not None, "Elemen utama harus ada"
    
    # 3. Validasi bahwa elemen utama BUKAN sidebar/nav
    # Scorer harus memilih <main> atau <article>, bukan <nav>
    main_tag_name = main_elem.name
    assert main_tag_name != 'nav', "Konten utama tidak boleh berupa tag <nav>"
    assert main_tag_name != 'aside', "Konten utama tidak boleh berupa tag <aside>"
    
    # 4. Ekstraksi dan Cek Konten Teks
    extractor = SemanticExtractor()
    blocks = extractor.extract_all(main_elem)
    
    all_text = " ".join([getattr(b, 'text', '') for b in blocks])
    full_content_str = str(main_elem)
    
    # Pastikan teks khas sidebar TIDAK ada di konten utama
    assert "Old Docs v1" not in all_text, "Link navigasi sidebar tidak boleh masuk ke konten"
    assert "Download PDF Version" not in all_text, "Iklan sidebar tidak boleh masuk ke konten"
    
    # Pastikan teks khas dokumentasi ADA di konten utama
    assert "Config Class Reference" in all_text, "Judul dokumentasi harus ada"
    assert "Lokasi file konfigurasi" in all_text, "Deskripsi tabel parameter harus ada"
    
    # 5. Validasi Tabel Parameter
    table_blocks = [
        b for b in blocks 
        if isinstance(b, TableBlock) or (hasattr(b, 'type') and str(b.type) in ['table', 'BlockType.TABLE'])
    ]
    
    assert len(table_blocks) > 0, "Tabel parameter harus diekstrak"
    
    # Cek isi tabel
    tbl = table_blocks[0]
    headers = getattr(tbl, 'headers', [])
    rows = getattr(tbl, 'rows', [])
    
    assert "Name" in headers or "Type" in headers, "Header tabel harus terekstrak"
    assert any("debug" in str(row) for row in rows), "Data baris tabel harus terekstrak"